baseURL = "https://chiasang.github.io/blog/"
languageCode = "zh-CN"
title = "XingJing"
theme = "hyde"
disqusShortname = ""
hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/:filename/"

[Menus]
  main = [
      {Name = "Archives", URL = "https://chiasang.github.io/blog/posts/"},
      {Name = "Tags", URL = "https://chiasang.github.io/blog/tags/"},
      {Name = "Photos", URL = "https://chiasang.github.io/blog/photos/"}
  ]

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description about this website
  description = "Keep Trying and Peaceful."

[params.valine]
  enable = false
    appId = ''
    appKey = ''
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true